version: '3.8'
services:
web:
build: .
command: flask run --host=0.0.0.0 --port=8000
volumes:
- ./:/app
environment:
- FLASK_APP=app.py
- FLASK_ENV=development
- REDIS_URL=redis://redis:6379/0
ports:
- "8000:8000"
depends_on:
- redis
redis:
image: redis:7-alpine
ports:
- "6379:6379"
worker:
build: .
command: celery -A celery_worker.celery worker --loglevel=info
volumes:
- ./:/app
environment:
- REDIS_URL=redis://redis:6379/0
depends_on:
- redis